require 'rubygems'

# Load Capistrano
load 'deploy'

# Load Genesis WordPress' recipes
Dir['bower_components/genesis-wordpress/deployment/*.rb'].each { |recipe| load(recipe) }

# Load <%= props.name %> recipes
load 'deployment/deploy'
